const floors=[{id:2,label:'2º andar'},{id:1,label:'1º andar'},{id:0,label:'Térreo'},{id:-1,label:'Subsolo'}];
const seedRooms=[
{id:'throne',name:'Sala do Trono',x:55,y:48,w:38,h:32,floor:2},{id:'corridor',name:'Corredor Norte',x:7,y:18,w:36,h:22,floor:2},{id:'study',name:'Escritório',x:7,y:49,w:36,h:30,floor:2},{id:'hall',name:'Grande Hall',x:12,y:19,w:76,h:58,floor:1},{id:'kitchen',name:'Cozinha',x:6,y:18,w:27,h:28,floor:0},{id:'tavern',name:'Salão da Taverna',x:38,y:15,w:55,h:62,floor:0}
];
const seedTokens={2:[{id:'carlos',emoji:'🧙',name:'Carlos',x:67,y:62,color:'#8b7cff',type:'Jogador',hp:'42 / 48'},{id:'lyra',emoji:'🧝',name:'Lyra',x:77,y:68,color:'#6ee7b7',type:'Jogador',hp:'37 / 40'},{id:'guard',emoji:'🛡️',name:'Guarda',x:89,y:55,color:'#e8c986',type:'NPC',hp:'20 / 20'}],1:[{id:'kael',emoji:'🧙‍♂️',name:'Kael',x:55,y:48,color:'#7dd3fc',type:'Jogador',hp:'31 / 31'}],0:[{id:'marta',emoji:'👵',name:'Dona Marta',x:57,y:45,color:'#f3a8ca',type:'NPC',hp:'—'}],'-1':[{id:'goblin',emoji:'👾',name:'Goblin',x:51,y:52,color:'#fb7185',type:'Criatura',hp:'8 / 8'}]};
const key='rpg-hub-world-v1'; let state=JSON.parse(localStorage.getItem(key)||'null')||{rooms:seedRooms,tokens:seedTokens,floor:2,selected:null,tool:'move'};
const $=id=>document.getElementById(id); const floorById=id=>floors.find(f=>f.id===id); const allTokens=()=>Object.values(state.tokens).flat();
function persist(){localStorage.setItem(key,JSON.stringify(state));}
function toast(msg){const el=$('toast');el.textContent='✓ '+msg;el.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>el.classList.remove('show'),1700)}
function renderFloors(){ $('floorSwitch').innerHTML=floors.map(f=>`<button class="${state.floor===f.id?'chosen':''}" onclick="changeFloor(${f.id})">${f.label}</button>`).join(''); $('floorName').textContent=floorById(state.floor).label.toUpperCase(); $('contextFloor').textContent=floorById(state.floor).label; }
function renderRooms(){const rooms=state.rooms.filter(r=>r.floor===state.floor);$('roomLayer').innerHTML=rooms.map(r=>`<div class="room" style="left:${r.x}%;top:${r.y}%;width:${r.w}%;height:${r.h}%" onclick="roomToast('${escapeHtml(r.name)}')"><span>${escapeHtml(r.name)}</span><i></i><i></i><i></i><i></i></div>`).join('');$('roomList').innerHTML=rooms.map(r=>`<button class="roomItem" onclick="roomToast('${escapeHtml(r.name)}')"><span class="roomIcon">▧</span><div><b>${escapeHtml(r.name)}</b><small>Estrutura salva</small></div><span>›</span></button>`).join('')||'<div class="emptySelect">Nenhum cômodo neste andar.</div>';}
function renderTokens(){const tokens=state.tokens[state.floor]||[];$('entityCount').textContent=tokens.length;$('tokenLayer').innerHTML=tokens.map(t=>`<div class="tokenBig ${state.selected===t.id?'selected':''}" draggable="true" data-id="${t.id}" style="left:${t.x}%;top:${t.y}%;--token-color:${t.color}"><div>${t.emoji}</div><span>${escapeHtml(t.name)}</span></div>`).join('');$('entityList').innerHTML=tokens.map(t=>`<button class="entityItem ${state.selected===t.id?'entityChosen':''}" onclick="selectToken('${t.id}')"><span class="entityAvatar" style="background:${t.color}">${t.emoji}</span><div><b>${escapeHtml(t.name)}</b><small>${t.type}</small></div><span>${state.selected===t.id?'●':'○'}</span></button>`).join('')||'<div class="emptySelect">Nenhuma entidade neste andar.</div>'; bindDrags(); renderSelected();}
function renderSelected(){const t=allTokens().find(x=>x.id===state.selected); if(!t){$('selectedCard').innerHTML='<div class="emptySelect">Selecione uma entidade na mesa para ver detalhes.</div>';return;} const current=floors.find(f=>state.tokens[f.id]?.some(x=>x.id===t.id));$('selectedCard').innerHTML=`<div class="eyebrow">SELECIONADO</div><div class="selectedRow"><div class="selectedEmoji">${t.emoji}</div><div><h3>${escapeHtml(t.name)}</h3><p>Posição persistente · ${current?current.label:'—'}</p></div></div><div class="statGrid"><div><span>STATUS</span><b>Ativo</b></div><div><span>HP</span><b>${t.hp}</b></div></div>`}
function bindDrags(){document.querySelectorAll('.tokenBig').forEach(el=>{el.addEventListener('click',e=>{e.stopPropagation();selectToken(el.dataset.id)});el.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',el.dataset.id);state.dragging=el.dataset.id});});$('board').ondragover=e=>{if(state.tool==='move')e.preventDefault()};$('board').ondrop=e=>{if(state.tool!=='move')return;e.preventDefault();const id=e.dataTransfer.getData('text/plain')||state.dragging;if(!id)return;const r=$('board').getBoundingClientRect();const x=Math.max(4,Math.min(96,((e.clientX-r.left)/r.width)*100));const y=Math.max(6,Math.min(94,((e.clientY-r.top)/r.height)*100));state.tokens[state.floor]=(state.tokens[state.floor]||[]).map(t=>t.id===id?{...t,x,y}:t);persist();renderTokens();toast('Posição atualizada');};}
function selectToken(id){state.selected=id;persist();renderTokens();}
function changeFloor(id){state.floor=id;state.selected=null;persist();renderAll();toast('Andar alterado')}
function roomToast(name){toast(name+' · estrutura salva')}
function addRoom(){const name=prompt('Nome do novo cômodo','Novo cômodo');if(!name?.trim())return;state.rooms.push({id:crypto.randomUUID(),name:name.trim(),x:46,y:24,w:34,h:30,floor:state.floor});persist();renderAll();toast(name.trim()+' criado')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderAll(){renderFloors();renderRooms();renderTokens();}

let drawStart=null;
$('board').addEventListener('pointerdown',e=>{if(state.tool!=='draw')return;const r=$('board').getBoundingClientRect();drawStart={x:e.clientX-r.left,y:e.clientY-r.top}});
$('board').addEventListener('pointerup',e=>{if(state.tool!=='draw'||!drawStart)return;const r=$('board').getBoundingClientRect();const x2=e.clientX-r.left,y2=e.clientY-r.top;const x=Math.min(drawStart.x,x2)/r.width*100,y=Math.min(drawStart.y,y2)/r.height*100,w=Math.max(12,Math.abs(x2-drawStart.x)/r.width*100),h=Math.max(12,Math.abs(y2-drawStart.y)/r.height*100);drawStart=null;const name=prompt('Nome do novo cômodo','Novo cômodo');if(!name?.trim())return;state.rooms.push({id:crypto.randomUUID(),name:name.trim(),x,y,w,h,floor:state.floor});persist();state.tool='move';$('moveBtn').classList.add('chosen');$('structureBtn').classList.remove('chosen');renderAll();toast(name.trim()+' criado');});
$('newRoom').addEventListener('click',addRoom);$('saveBtn').addEventListener('click',()=>{persist();toast('Mundo salvo')});$('discordBtn').addEventListener('click',()=>toast('Abrindo Discord…'));$('discordTop').addEventListener('click',()=>toast('Abrindo Discord…'));$('moveBtn').addEventListener('click',()=>{state.tool='move';$('moveBtn').classList.add('chosen');$('structureBtn').classList.remove('chosen');toast('Modo mover ativo')});$('structureBtn').addEventListener('click',()=>{state.tool='draw';$('structureBtn').classList.add('chosen');$('moveBtn').classList.remove('chosen');toast('Modo estrutura preparado')});renderAll();window.changeFloor=changeFloor;window.selectToken=selectToken;window.roomToast=roomToast;
